version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - PORT=8000
      - BASE_DOMAIN=localhost:8000
      - ALLOWED_HOSTS=localhost,127.0.0.1
    volumes:
      - ./config:/app/config 