services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - PORT=8000
      - BASE_DOMAIN=localhost:8000
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DATABASE_URL=postgresql://kcdd_user:kcdd_password@db:5432/kcdd_market
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=kcdd_market
      - DB_USER=kcdd_user
      - DB_PASSWORD=kcdd_password
    volumes:
      - ./config:/app/config
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=kcdd_market
      - POSTGRES_USER=kcdd_user
      - POSTGRES_PASSWORD=kcdd_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kcdd_user -d kcdd_market"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 