# Generated by Django 5.2.5 on 2025-08-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_donor_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this challenge category')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Challenge categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='request',
            name='program_region_county',
            field=models.CharField(blank=True, help_text='Program / Services Region (County)', max_length=100),
        ),
        migrations.AddField(
            model_name='request',
            name='program_region_metro',
            field=models.CharField(blank=True, help_text='Program / Services Region (Metro)', max_length=100),
        ),
        migrations.AddField(
            model_name='request',
            name='challenge_categories',
            field=models.ManyToManyField(blank=True, help_text='How might you categorize the challenge(s) faced by those you serve? (Check all that apply)', to='app.challengecategory'),
        ),
    ]
