# Generated by Django 5.2.5 on 2025-08-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_challengecategory_request_program_region_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='program_region_metro',
            field=models.CharField(blank=True, choices=[('all_kc_metro', 'All KC Metro'), ('kc_metro_mo', 'KC Metro - MO Only'), ('kc_metro_ks', 'KC Metro - KS Only')], help_text='Program / Services Region (Metro)', max_length=20),
        ),
    ]
