# Generated by Django 5.2.5 on 2025-08-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_request_program_region_metro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='program_region_county',
            field=models.CharField(blank=True, choices=[('cass_mo', 'Cass (MO)'), ('clay_mo', 'Clay (MO)'), ('jackson_mo', 'Jackson (MO)'), ('lafayette_mo', 'Lafayette (MO)'), ('platte_mo', 'Platte (MO)'), ('ray_mo', 'Ray (MO)'), ('johnson_ks', 'Johnson (KS)'), ('leavenworth_ks', 'Leavenworth (KS)'), ('wyandotte_ks', 'Wyandotte (KS)')], help_text='Program / Services Region (County)', max_length=20),
        ),
    ]
