# Generated by Django 5.2.5 on 2025-08-30 03:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_request_program_region_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='denial_reason',
            field=models.TextField(blank=True, help_text='Reason for denial (if request was denied)'),
        ),
        migrations.AddField(
            model_name='request',
            name='denied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('fulfilled', 'Fulfilled'), ('denied', 'Denied')], default='open', max_length=10),
        ),
        migrations.CreateModel(
            name='RequestNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('denied', 'Request Denied'), ('approved', 'Request Approved'), ('claimed', 'Request Claimed'), ('fulfilled', 'Request Fulfilled'), ('edited', 'Request Edited')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_notifications', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.request')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
